nodeLinker: pnp

packageExtensions:
  styled-components@*:
    dependencies:
      react-is: ^18.2.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
